### PR TITLE
Add symbol for DeleteLogFileActionDescriptor

### PR DESCRIPTION
**Pull request by mtughan**
To make deleting the log file simpler from pipeline code, add a symbol
to its descriptor.

Modify the unit tests for the descriptors so they verify that the
descriptor symbol is registered and available.

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mtughan** [comment]
@damianszczepanik, can you review and merge?

**Comment by damianszczepanik** [comment]
CI has failed

**Comment by mtughan** [comment]
@damianszczepanik, only the build on AppVeyor failed, and with a network-related failure, not anything related to the code.

```
[ERROR] Failed to execute goal on project build-history-manager: Could not resolve dependencies for project pl.damianszczepanik:build-history-manager:hpi:1.3.1-SNAPSHOT: Failed to collect dependencies at org.jenkins-ci.main:jenkins-war:war:2.204: Failed to read artifact descriptor for org.jenkins-ci.main:jenkins-war:war:2.204: Could not transfer artifact org.jenkins-ci.main:jenkins-war:pom:2.204 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/public/): Transfer failed for https://repo.jenkins-ci.org/public/org/jenkins-ci/main/jenkins-war/2.204/jenkins-war-2.204.pom: Connection reset -> [Help 1]
```

I don't see a way to retrigger the AppVeyor build, so I'm not sure what the expected next step here is.

**Comment by damianszczepanik** [comment]
Rerun the build, now is green!

What I'd like to have is to some example in README file how to use new feature

**Comment by damianszczepanik** [comment]
And test coverage - I haven't check that so far

**Comment by mtughan** [comment]
Test coverage should be there already by making sure we can pull the descriptor by its symbol. I've tested this and verified that it fails if the symbol is missing.

I can add an example to the `README` with the new symbol and examples of all the actions (as only the delete build action is currently covered).

**Pull request merged**
